const state={test:null,index:0,answers:{},order:[],student:localStorage.getItem('io_student')||''};
const $=s=>document.querySelector(s);
const home=$('#homeView'),exam=$('#examView'),result=$('#resultView');
$('#studentName').value=state.student;
function esc(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#039;','"':'&quot;'}[c]))}
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}
$('#saveName').onclick=()=>{state.student=$('#studentName').value.trim();localStorage.setItem('io_student',state.student);toast('تم حفظ الاسم')}
function storageKey(id){return 'io_exam_'+id}
function resultKey(id){return 'io_result_'+id}
function shuffle(a){a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a}
function renderCards(){const grid=$('#testsGrid');grid.innerHTML='';TESTS.forEach(t=>{const saved=JSON.parse(localStorage.getItem(storageKey(t.id))||'null');const done=JSON.parse(localStorage.getItem(resultKey(t.id))||'null');const count=saved?Object.keys(saved.answers||{}).length:0;const c=document.createElement('article');c.className='test-card';c.innerHTML=`<div class="test-number">${String(t.id).padStart(2,'0')}</div><div class="test-info"><h4>${esc(t.title)}</h4><p>${esc(t.subtitle)}</p><div class="meta"><span class="tag">50 سؤالاً</span><span class="tag">صح / خطأ</span>${done?`<span class="tag">آخر نتيجة: ${done.score}/50</span>`:count?`<span class="tag">محفوظ: ${count}/50</span>`:''}</div></div><button class="card-action" aria-label="بدء الاختبار">←</button>`;c.onclick=()=>startTest(t.id);grid.appendChild(c)})}
function startTest(id){const t=TESTS.find(x=>x.id===id);const saved=JSON.parse(localStorage.getItem(storageKey(id))||'null');state.test=t;state.answers=saved?.answers||{};state.order=saved?.order?.length===50?saved.order:shuffle(t.questions.map((_,i)=>i));state.index=saved?.index||0;saveProgress();home.classList.add('hidden');result.classList.add('hidden');exam.classList.remove('hidden');renderQuestion();window.scrollTo({top:0})}
function saveProgress(){if(!state.test)return;localStorage.setItem(storageKey(state.test.id),JSON.stringify({answers:state.answers,order:state.order,index:state.index}))}
function currentQ(){return state.test.questions[state.order[state.index]]}
function answerBtnClass(btnValue,q){const userAns=state.answers[q.id];const answered=userAns!==undefined;let cls='answer-btn';if(userAns===btnValue)cls+=' selected';if(answered){cls+=' locked';if(q.answer===btnValue)cls+=' correct';if(userAns===btnValue&&q.answer!==btnValue)cls+=' wrong';}return cls}
function feedbackHTML(q){const userAns=state.answers[q.id];if(userAns===undefined)return '';const ok=userAns===q.answer;const correctLabel=q.answer?'صح':'خطأ';return `<div class="instant-feedback ${ok?'ok':'bad'}"><div class="status">${ok?'✅ إجابة صحيحة':'❌ إجابة غير صحيحة'}</div><div>الإجابة الصحيحة: <span class="correct-answer">${correctLabel}</span></div><span class="exp">${esc(q.explanation||'')}</span></div>`}
function renderQuestion(){const answered=Object.keys(state.answers).length;const q=currentQ();const locked=state.answers[q.id]!==undefined;exam.innerHTML=`<div class="exam-shell"><aside class="exam-side"><h3>${esc(state.test.title)}</h3><p>${esc(state.test.subtitle)}</p><div class="student">الطالب: <strong>${esc(state.student||'غير مسجل')}</strong></div><div class="progress-wrap"><div class="progress-label"><span>التقدم</span><span>${answered}/50</span></div><div class="progress"><div style="width:${answered*2}%"></div></div></div><div class="q-nav" id="qNav"></div><button class="danger-link" id="exitBtn">حفظ وخروج</button></aside><article class="question-card"><div class="q-kicker">السؤال ${state.index+1} من 50</div><h2>${esc(q.statement)}</h2><div class="answer-grid"><button class="${answerBtnClass(true,q)}" data-v="true" ${locked?'disabled':''}><span class="answer-icon">✓</span>صح</button><button class="${answerBtnClass(false,q)}" data-v="false" ${locked?'disabled':''}><span class="answer-icon">✕</span>خطأ</button></div>${feedbackHTML(q)}<div class="question-footer"><button class="navbtn prev" id="prevBtn" ${state.index===0?'disabled':''}>السابق</button><button class="navbtn next" id="nextBtn">${state.index===49?'مراجعة الإنهاء':'التالي'}</button></div>${answered===50?'<div class="submit-row"><button class="submit" id="submitBtn">إنهاء الاختبار وإظهار النتيجة</button></div>':''}</article></div>`;
 const nav=$('#qNav');state.order.forEach((qi,i)=>{const item=state.test.questions[qi];const was=state.answers[item.id];const correct=was!==undefined&&was===item.answer;const wrong=was!==undefined&&was!==item.answer;const b=document.createElement('button');b.className='q-dot'+(was!==undefined?' answered':'')+(i===state.index?' current':'')+(correct?' correct':'')+(wrong?' wrong':'');b.textContent=i+1;b.onclick=()=>{state.index=i;saveProgress();renderQuestion()};nav.appendChild(b)});
 document.querySelectorAll('.answer-btn').forEach(b=>b.onclick=()=>{if(state.answers[q.id]!==undefined)return;state.answers[q.id]=b.dataset.v==='true';saveProgress();renderQuestion()});
 $('#prevBtn').onclick=()=>{if(state.index>0){state.index--;saveProgress();renderQuestion()}};
 $('#nextBtn').onclick=()=>{if(state.index<49){state.index++;saveProgress();renderQuestion()}else if(Object.keys(state.answers).length<50){const first=state.order.findIndex(qi=>state.answers[state.test.questions[qi].id]===undefined);if(first>=0){state.index=first;saveProgress();renderQuestion();toast('أكمل الأسئلة غير المجابة')}}};
 $('#exitBtn').onclick=goHome;const s=$('#submitBtn');if(s)s.onclick=submitTest;
}
function submitTest(){if(Object.keys(state.answers).length<50){toast('يرجى الإجابة عن جميع الأسئلة');return}let score=0;state.test.questions.forEach(q=>{if(state.answers[q.id]===q.answer)score++});localStorage.setItem(resultKey(state.test.id),JSON.stringify({score,date:new Date().toISOString()}));localStorage.removeItem(storageKey(state.test.id));renderResult(score)}
function renderResult(score){exam.classList.add('hidden');result.classList.remove('hidden');const pct=Math.round(score*2);const level=pct>=90?'ممتاز':pct>=80?'جيد جداً':pct>=70?'جيد':pct>=60?'مقبول':'يحتاج إلى مراجعة';const ordered=state.order.map(i=>state.test.questions[i]);result.innerHTML=`<article class="result-card"><div class="score-circle" style="--pct:${pct}%"><div class="score-inner"><b>${score}/50</b><span>${pct}%</span></div></div><h2>${level}</h2><p class="result-summary">${esc(state.student||'الطالب')}، أنهيت ${esc(state.test.title)}. راجع البنود أدناه لتثبيت المعلومات.</p><div class="result-actions"><button class="primary" id="homeBtn">العودة للاختبارات</button><button class="secondary" id="retryBtn">إعادة الاختبار</button><button class="secondary" onclick="window.print()">طباعة النتيجة</button></div><div class="review"><h3>المراجعة التفصيلية</h3>${ordered.map((q,i)=>{const ok=state.answers[q.id]===q.answer;return `<div class="review-item ${ok?'correct':'wrong'}"><h4>${i+1}. ${esc(q.statement)}</h4><div class="review-meta">إجابتك: <b>${state.answers[q.id]?'صح':'خطأ'}</b> | الإجابة الصحيحة: <b>${q.answer?'صح':'خطأ'}</b><br>${esc(q.explanation)}</div></div>`}).join('')}</div></article>`;$('#homeBtn').onclick=goHome;$('#retryBtn').onclick=()=>{state.answers={};state.order=shuffle(state.test.questions.map((_,i)=>i));state.index=0;localStorage.removeItem(storageKey(state.test.id));exam.classList.remove('hidden');result.classList.add('hidden');saveProgress();renderQuestion();window.scrollTo({top:0})};window.scrollTo({top:0})}
function goHome(){exam.classList.add('hidden');result.classList.add('hidden');home.classList.remove('hidden');renderCards();window.scrollTo({top:0})}
renderCards();
